import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../contexts/ThemeContext';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By downloading, installing, or using Replyr, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the app.',
  },
  {
    title: '2. Description of Service',
    body: 'Replyr is an AI-powered direct message generation tool designed to help users craft effective outreach messages. The service uses third-party AI to generate content based on user inputs.',
  },
  {
    title: '3. User Responsibilities',
    body: 'You are responsible for all content you generate using Replyr. You agree not to use the service to send spam, harass individuals, or violate any applicable laws. You are solely responsible for how you use generated messages.',
  },
  {
    title: '4. Intellectual Property',
    body: 'Messages generated by Replyr using your inputs are considered your content. Replyr retains no ownership over generated messages. The Replyr app, branding, and underlying technology remain the intellectual property of Replyr.',
  },
  {
    title: '5. Free and Pro Plans',
    body: 'Replyr offers a free tier with limited daily generations and a Pro subscription with unlimited access. Subscription fees are billed through the App Store or Google Play. Cancellations take effect at the end of the current billing period.',
  },
  {
    title: '6. Disclaimer of Warranties',
    body: 'Replyr is provided "as is" without warranties of any kind. We do not guarantee that generated messages will achieve specific results such as getting replies. AI outputs may vary and should be reviewed before sending.',
  },
  {
    title: '7. Limitation of Liability',
    body: 'To the maximum extent permitted by law, Replyr shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.',
  },
  {
    title: '8. Changes to Terms',
    body: 'We reserve the right to modify these Terms at any time. We will notify users of significant changes within the app. Continued use of Replyr after changes constitutes acceptance.',
  },
  {
    title: '9. Contact',
    body: 'For questions about these Terms, contact us at legal@replyr.app.',
  },
];

export default function TermsScreen() {
  const { colors } = useTheme();

  return (
    <SafeAreaView style={[styles.safe, { backgroundColor: colors.bg }]}>
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.back}>
          <Ionicons name="arrow-back" size={22} color={colors.textSec} />
        </TouchableOpacity>
        <Text style={[styles.title, { color: colors.text }]}>Terms of Service</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <Text style={[styles.updated, { color: colors.textMuted }]}>Last updated: April 2026</Text>
        <Text style={[styles.intro, { color: colors.textSec }]}>
          These Terms of Service govern your use of Replyr. Please read them carefully before using
          the app.
        </Text>

        {SECTIONS.map((s) => (
          <View key={s.title} style={styles.section}>
            <Text style={[styles.sectionTitle, { color: colors.text }]}>{s.title}</Text>
            <Text style={[styles.sectionBody, { color: colors.textSec }]}>{s.body}</Text>
          </View>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  back: { width: 40 },
  title: { fontSize: 17, fontWeight: '700' },
  scroll: { flex: 1 },
  content: {
    padding: 24,
    paddingBottom: 48,
    maxWidth: 640,
    alignSelf: 'center',
    width: '100%',
  },
  updated: { fontSize: 12, marginBottom: 12 },
  intro: { fontSize: 15, lineHeight: 24, marginBottom: 24 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 15, fontWeight: '700', marginBottom: 8 },
  sectionBody: { fontSize: 14, lineHeight: 22 },
});
