import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../contexts/ThemeContext';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By downloading, installing, or using Replyr ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the App. These Terms form a legally binding agreement between you and Replyr.',
  },
  {
    title: '2. Eligibility',
    body: 'You must be at least 13 years old to use Replyr. By using the App, you confirm that you meet this requirement. If you are under 18, you confirm that you have obtained consent from a parent or legal guardian.',
  },
  {
    title: '3. Description of Service',
    body: 'Replyr is an AI-powered direct message generation tool that helps users craft outreach messages. The service uses third-party AI providers to generate content based on user inputs. We do not guarantee that generated messages will achieve specific results such as replies or conversions.',
  },
  {
    title: '4. User Accounts',
    body: 'You agree to provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You must notify us immediately of any unauthorized access at support@replyr.app.',
  },
  {
    title: '5. Acceptable Use',
    body: 'You agree not to use Replyr to: (a) send spam or unsolicited mass messages; (b) harass, threaten, or harm any individual; (c) violate any applicable local, national, or international laws; (d) generate abusive, illegal, or discriminatory content; (e) attempt to reverse-engineer or exploit the App; (f) use the App in any way that could damage, disable, or impair the service.',
  },
  {
    title: '6. Content Ownership',
    body: 'Messages generated by Replyr using your inputs are considered your content. You retain full ownership of any generated output. Replyr claims no ownership over messages you generate. By using the service, you grant Replyr a limited, non-exclusive license to process your inputs solely for the purpose of delivering the service.',
  },
  {
    title: '7. Free Tier and Subscriptions',
    body: 'Replyr offers a free tier with a limited number of lifetime generations. Pro subscriptions are available for unlimited access. All subscription fees are processed through Apple App Store or Google Play. Prices are displayed at the time of purchase. Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current billing period. You can manage or cancel your subscription through your device\'s App Store account settings.',
  },
  {
    title: '8. Refund Policy',
    body: 'Refunds are handled according to the refund policy of Apple App Store or Google Play. We do not process refunds directly. For disputes, please contact the respective app store.',
  },
  {
    title: '9. Disclaimer of Warranties',
    body: 'Replyr is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the service will be uninterrupted, error-free, or that AI-generated content will be accurate or suitable for any specific purpose. Use of generated messages is entirely at your own risk.',
  },
  {
    title: '10. Limitation of Liability',
    body: 'To the fullest extent permitted by applicable law, Replyr and its owners, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the App, including but not limited to loss of data, revenue, or business opportunities. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.',
  },
  {
    title: '11. Termination',
    body: 'We reserve the right to suspend or terminate your account at any time, with or without notice, if you violate these Terms or engage in conduct harmful to other users or the service. You may delete your account at any time through the App settings.',
  },
  {
    title: '12. Changes to Terms',
    body: 'We reserve the right to update these Terms at any time. We will notify you of significant changes via the App or email. Continued use of Replyr after changes constitutes acceptance of the updated Terms. If you do not agree to the updated Terms, you must stop using the App.',
  },
  {
    title: '13. Governing Law',
    body: 'These Terms are governed by and construed in accordance with the laws of the Netherlands. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the competent courts in the Netherlands, without prejudice to your rights as a consumer under mandatory EU consumer protection law.',
  },
  {
    title: '14. Severability',
    body: 'If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.',
  },
  {
    title: '15. Contact',
    body: 'For questions about these Terms, contact us at: support@replyr.app. We aim to respond within 5 business days.',
  },
];

export default function TermsScreen() {
  const { colors } = useTheme();

  return (
    <SafeAreaView style={[styles.safe, { backgroundColor: colors.bg }]}>
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.back}>
          <Ionicons name="arrow-back" size={22} color={colors.textSec} />
        </TouchableOpacity>
        <Text style={[styles.title, { color: colors.text }]}>Terms of Service</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <Text style={[styles.updated, { color: colors.textMuted }]}>Last updated: April 12, 2026</Text>
        <Text style={[styles.intro, { color: colors.textSec }]}>
          Please read these Terms of Service carefully before using Replyr. They govern your use of the
          App and form a legally binding agreement between you and Replyr.
        </Text>

        {SECTIONS.map((s) => (
          <View key={s.title} style={styles.section}>
            <Text style={[styles.sectionTitle, { color: colors.text }]}>{s.title}</Text>
            <Text style={[styles.sectionBody, { color: colors.textSec }]}>{s.body}</Text>
          </View>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  back: { width: 40 },
  title: { fontSize: 17, fontWeight: '700' },
  scroll: { flex: 1 },
  content: {
    padding: 24,
    paddingBottom: 48,
    maxWidth: 640,
    alignSelf: 'center',
    width: '100%',
  },
  updated: { fontSize: 12, marginBottom: 12 },
  intro: { fontSize: 15, lineHeight: 24, marginBottom: 24 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 15, fontWeight: '700', marginBottom: 8 },
  sectionBody: { fontSize: 14, lineHeight: 22 },
});
